version: "3.9"

networks:
  border_link:
    internal: false

volumes:
  postgres_data:
      name: border_link_postgres_data
  redis_data:
      name: border_link_redis_data

services:
  postgres:
    image: postgres:16.4-alpine
    container_name: ${APP_NAME}_db
    restart: unless-stopped
    env_file:
        -   .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    networks:
      - border_link
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    env_file:
        -   .env
    container_name: ${APP_NAME}_redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - border_link
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: border_link_api
    container_name: ${APP_NAME}_api
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - border_link
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
      # - "5678:5678" # Uncomment if using debug
    command: gunicorn --workers ${GUNICORN_WORKERS:-4} --bind 0.0.0.0:8000 main_system.wsgi:application
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - postgres
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  borderlink_celery:
    image: border_link_api
    container_name: borderlink_celery
    restart: unless-stopped
    working_dir: /src
    env_file:
      - .env
    networks:
      - border_link
    command: celery -A main_system worker --loglevel=info --concurrency=4
    depends_on:
      - redis
      - postgres

  borderlink_celery_beat:
    image: border_link_api
    container_name: borderlink_celery_beat
    restart: unless-stopped
    working_dir: /src
    env_file:
      - .env
    networks:
      - border_link
    command: celery -A main_system beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    depends_on:
      - redis
      - postgres

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - border_link
